### ISSUE TITLE
[TableToolbar] icons in buttons are wrong size, refactor to use stock icon only button

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#1174]
[Internal Watson-IoT/pal-tracking#407](https://github.ibm.com/Watson-IoT/pal-tracking/issues/407)

### Describe the bug

The buttons in the table toolbar are too big. They should be using stock buttons with `hasIconOnly`, these use icons of size `16`. We're using size `20`.

@lukefirth I'd like your approval on this one. I opened a similar issue on Carbon about the pagination component: https://github.com/carbon-design-system/carbon/issues/6057

### To Reproduce

1. Go to the [`Table/stateful example with expansion and column resize`](https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--stateful-example-with-expansion-and-column-resize) story
![image](https://user-images.githubusercontent.com/3360588/81584249-1ff91e80-9378-11ea-9714-2c31e62b75c5.png)

### Expected behavior
Using a stock Button with hasIconOnly prop, these should be using the size 16 icons.

![image](https://user-images.githubusercontent.com/3360588/81584619-97c74900-9378-11ea-9efa-63e24f8d2c91.png)

### Environment/versions:

- `carbon-addons-iot-react` version: `v2.76.7`

### Items to complete

- [ ] Refactor to remove the `src/components/Table/TableToolbar/TableToolbarSVGButton.jsx` introduced in #1165 (related convo [here](https://github.com/IBM/carbon-addons-iot-react/pull/1165#discussion_r423159362))
- [ ] Utilize a `Button` instead, like:
```
<Button
  kind={'ghost'}
  onClick={onToggleFilter}
  testId="TableToolbar-filter-button"
  renderIcon={Filter16}
  iconDescription={i18n.filterButtonAria}
  hasIconOnly
  tooltipAlignment={'end'}
  tooltipPosition={'bottom'}
/>
```
- [ ] Resolve any style defects of icon coloring
- [ ] Ensure tooltip placement is not effected by table z-index or similar

**Comment by tay1orjones** [comment]
FWIW it appears that the carbon data table toolbar icon buttons use size 16 icons

https://react.carbondesignsystem.com/?path=/story/datatable--with-batch-actions

I'm not sure why we deviated?

**Comment by lukefirth** [comment]
No clue - looking at our sketch library, we use 16px icons for the table toolbar too. 
![image](https://user-images.githubusercontent.com/30671949/81717643-6a45d280-9440-11ea-92cc-08e8c806cd1c.png)

**Comment by scottdickerson** [comment]
@CynZhang has also requested that the Icons show the IconTooltip over their icon with an explanation of what each icon uses.

**Comment by lukefirth** [comment]
For sure, as a rule in general whenever we use icon buttons we should use icon tooltips at the very least to make up for lack of labellingOn 14 May 2020 12:07, Scott Dickerson <notifications@github.com> wrote:
@CynZhang has also requested that the Icons show the IconTooltip over their icon with an explanation of what each icon uses.

**Comment by CynZhang** [comment]
In addition to that, is this also going to address the icon states issue? https://github.ibm.com/Watson-IoT/pal-tracking/issues/399
