### ISSUE TITLE
[v2]: Upgrade Components to Carbon v10

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#154]
Containing issue for the migration of our components to Carbon v10

High level steps/pieces:
- [x] upgrade carbon deps
- [x] upgrade storybook to v5 to support new prop-type definitions
- [x] Update/Fix Components
    - [x] `ButtonEnhanced` refactored to `Button` wrapper
    - [ ] ~`Table` renamed to `DataTable`, ensure sub components exported in the same fashion as Carbon to support custom composition of components. Avoid any breaking change from Carbon's documentation/usage for `DataTable`~
- [x] review visually for defects, fix as necessary
- [ ] ... 

Maximo needs it and we need to support downstream teams

**Comment by tay1orjones** [comment]
_Originally posted by @lukefirth in https://github.com/IBM/carbon-addons-iot-react/pull/300#issuecomment-501221567_:

Ok, you asked for the firehose and my under the microscope review. Feel free to break these up and handle them however.  Here goes:

------


# V10 Component Upgrade review

**1. Add card**
- I propose a slight styling update to match duo examples better here. (@amymillett please feel free to override me here)
![image](https://user-images.githubusercontent.com/30671949/59343751-768f5000-8d04-11e9-90b0-35a5b15e0afa.png)


**2. Base modal - Danger**
- I think the red bar at the top shouldn’t be there:
![image](https://user-images.githubusercontent.com/30671949/59343897-bd7d4580-8d04-11e9-8974-efd9e9da9ee4.png)


**3. Base Modal - Error states**
- Should be padding to the left and right, I believe the same as what you see for the title and X, rather than 100% of the modal width
![image](https://user-images.githubusercontent.com/30671949/59344343-c9b5d280-8d05-11e9-81a1-dfce4543dacb.png)


**4. Base modal - add description**
- Not seeing the description

**5. Header action buttons with drop downs**
- Not for this, but capturing for posterity - we should look at swapping the drop down types to right panel components.

**6. Wizardinline - Stateful example**
- Gaps between the progress indicator steps. I think in Duo they have them no longer spanning the container but all touching and left aligned.
- Title of step cut off, ‘Device inform’ in this example. Meant to wrap I believe.
- Close icon seems much heavier than the normal icon.
- Title and progress indicator look to be a long way from the top of the modal, a ‘line’ down from the ‘line’ with the close icon. I would expect these to be on the same line, meaning a similar padding between the top of the inline and the title as seen in modals. eg:
![image](https://user-images.githubusercontent.com/30671949/59345077-472e1280-8d07-11e9-95d5-2d012b36656f.png)
@amymillett again, please feel free to override me here, I've not seen if there is a finalised V10 design for this we should be aiming for, these are just my comments on how I'd expect to respond to the current.

**7. Navigation bar - Normal**
-  Again not something for now, but for posterity. For the nav pattern stuff, we will be moving the tabs from the top of the navigation bar to the bottom of it, just above the page content.

**8. Navigation bar - Example with work area.**
- Text at the top says to click the new entity type button to interact with a work area, but nothing actually happens when I click the button.

**9. Page hero - normal with action.**
- This example seems to be a page hero with a content switcher, so the ‘with action’ name might be a touch misleading.
- The spacing on the content switcher seems off, its rendering super wide, I think there might need to be a max width set per ‘segment’. Although I can’t eyeball what a reasonable one would be.

**10. Page hero - with section**
- This is a slight design change (so feel free to take out of here and we can track elsewhere), but this may be a good time to replace the ‘Explore/‘ with a traditional breadcrumb above the page title.

**11. Progress indicator - Stateful**
- Same comment as in the modal examples, it seems like we’re spacing each step out to fill the width of the container, but carbon recommendation is that we ‘connect’ them by left aligning.
![image](https://user-images.githubusercontent.com/30671949/59345231-9c6a2400-8d07-11e9-87ec-5b0e99664f68.png)


**12. Progress indicator - Vertical**
- Not sure if this is us or not, but the vertical spacing between steps is quite high. In the usage & style guidance carbon doesn’t talk about this for vertical so we’re on our own. I’d suggest we drop it to ~75% of what the example shows.

**13. Resource list - with action**
- On wider windows, the actions seem to be a little way ‘in’ to the list rather than anchored to the right hand side with a fixed padding. I believe it would be better if we set a fixed distance from the right hand edge of the list itself (including the row dividers) and the right hand side of the action… I guess just right aligning the action in the component.

**14. Side nav - Sidenav component.**
- Only thing here would be to reflect the hamburger saga. I personally would say go with Carbon (hamburger turns to X when open), but you heard the resistance to that. So to follow the party line, we should retain the hamburger icon in both open and closed states
![image](https://user-images.githubusercontent.com/30671949/59345347-cf141c80-8d07-11e9-8a0c-76f0eaec608b.png)


**15. Simplepagination**
- Looks like it just needs a style update to reflect V10 https://www.carbondesignsystem.com/components/pagination/code

**16. Table - Simple stateful example**
- Checkboxes are slight off in vertical alignment
![image](https://user-images.githubusercontent.com/30671949/59345397-ec48eb00-8d07-11e9-883d-3ecf5ba80c03.png)


**17. Table - Stateful example with expansion** 
- Spacing between the filter inputs and the column titles they are filtering on could be reduced. Right now they look a little disconnected. Suggest 0 padding between the top of the filter input and the bottom of the table title ‘block’ (the bit that changes coloraturas on hover). ![image](https://user-images.githubusercontent.com/30671949/59345422-f79c1680-8d07-11e9-8904-3a0178d62ec6.png)


- Row height has gone quite large (not a problem in itself), but the content in the row should stay middle aligned vertically. Now the action and check look to be middle aligned, but the cell content is higher up. I noticed this isn’t happening on the simple example of expansion, but does happen again when I use the ‘row expansion with actions’ so I wonder if its the actions that are causing the weirdness to be introduced. 
![image](https://user-images.githubusercontent.com/30671949/59345479-16021200-8d08-11e9-931a-6903dafd24de.png)


- Column picker - I think we just need to provide you with a V10 styling of this @amymillet do you have this handy you can supply?


**18. Table with simple search**
- Search focus state is strangely tiny
![image](https://user-images.githubusercontent.com/30671949/59345494-231f0100-8d08-11e9-8506-42d5acd4c1e0.png)


**19. Table body row**
- I can see now from these examples, the row height changes depending on if there are actions and if they are running, error or just there, which I guess is what introduced the weirdness in the earlier example in (17)

**20. Table detail wizard stateful example**
- I think the styling here needs to be aligned with the inline wizard component for the close button, title and footer (eg the button width etc). I’m not sure which one is ‘right’ or if both need to adapt a bit. I don’t have the design to hand - @Amymillet is there a design for the table inline wizard and the traditional inline wizard handy we can share?

**21. Table detail wizard static with sidebar**
- In the example, I’m not seeing a difference between the static and static with sidebar versions aside from the main content going from text to the green box example. Am I missing something?

**22. Table detail wizard with error.**
- Same comment as (3) the base modal one. Padding on either side should be the same for the error as the general content in the wizard rather than 100% I believe.

**23. Tile catalog - default**
- Mainly just the pagination style, but we’ve got that noted earlier.
- I see the notes in the example on wrapping and truncation of title and description. I suggest:
- Title can go to 2 lines wrapped, then should truncate.
- Description will fill the rest of the available space with wrapping, but when it reaches the end, it should truncate. Generally we should in the UX patterns (that we’ve not written for this yet) recommend that these are used with character limited descriptions.

**24. Tile catalog  - with search**
- I suggest we drop the title from the component itself (like we don’t have the table title in the table component) and in its place, put the same search icon/behaviour (click to go into search mode) as in the table component https://deploy-preview-300--carbon-addons-iot-react.netlify.com/?path=/story/table--with-simple-search.

**25. Tile catalog - loading**
- Can we set the height of the tiles in loading state to be the same height as them once loaded?  I would treat the height of the tiles in the same way as row heights in the table with fixed options (thus the truncation I mentioned earlier). That way we can set the loading to be nice and smooth of just content filling in without a size change.

**26. WizardModal - basic**
- Same note as before about the pagination, it seems to be correctly left aligned here, but there are still small gaps between the steps.

**27. WizardModal - customfooter**
- We should treat the custom footer in the same way as we do with the inline wizard, where here we use a primary button to fill the example. Generally I expect this custom space to be used by small status indicators and more likely - short link style text to act as a tertiary action. There’s a flame war in Carbon about allowing tertiary actions or not, but Chris Conners is on the same thought process as us with these sorts of examples: 
![image](https://user-images.githubusercontent.com/30671949/59345630-6c6f5080-8d08-11e9-821d-4c2607312474.png)

Just change the labels to ‘remove’ ‘cancel’ ‘done’ and we’ve got the main AS pattern.

**Comment by davidicus** [comment]
- [x]  1. Add card
- [x] 2. Base modal - Danger
- [x] 3. Base Modal - Error states
- [x] 4. Base modal - add description
- [x] 5. Header action buttons with drop downs -  [issue](#322) created
- [ ] 6. Wizardinline - Stateful example
  - [ ] The carbon component is coded for these steps to expand the full width of their container. @lukefirth Do they specifically say that these should have no gaps or are we taking that stance regardless?
  - [ ] @lukefirth the default carbon behavior has these steps ellipsis on overflow with input having hover description. Will stay in line with Carbon unless you feel we should deviate.
  - [x] padding shortened. The steps being dynamic extend to the end of modal so being just below the x seems to make sense in the case of them being flush with the side so we can keep the same padding around. 
- [x] 7. Navigation bar - Normal - [issue](#239)
- [x] 8. Navigation bar - Example with work area.
- [x] 9. Page hero - normal with action.
  - [x] changed to with content switcher
  - [x] put max width on segments 
- [x] 10. Page hero - with section - [issue](#323) created
- [x] 11. Progress indicator - Stateful
- [x] 12. Progress indicator - Vertical
- [x] 13. Resource list - with action
- [ ] 14. Side nav - Sidenav component. -[issue](#324) created for hamburger
- [x] 15. Simplepagination 
- [ ] 16. Table - Simple stateful example
- [ ] 17. Table - Stateful example with expansion
  - [ ] padding between filter inputs and headers
  - [ ] Padding of cells when actions are present
  - [ ] Table - Stateful example with expansion
- [x] 18. Table with simple search
- [ ] 19. Table body row
- [ ] 20. Table detail wizard stateful example
- [ ] 21. Table detail wizard static with sidebar

  - [ ] Change Sidnav to use carbon's new styling with the acception of our icon open state @lukefirth can you confirm this?
- [ ] Update Header to use the new focus states from Carbon v10
- [ ]

**Comment by amymillett** [comment]
@davidicus @lukefirth 

I think Luke has covered a lot of the things I've noticed, but a few more notes... (I'm looking at https://beta.carbon-addons-iot-react.com)

**1. Tile**

- @lukefirth was there a reason that our tile has a different hover state than the regular old Carbon one?

**2. Filedrop - Drag and Drop**
- Link style needs to be updated to #0062ff blue

**3. Wizard Inline**

![Screen Shot 2019-06-20 at 3 22 39 PM](https://user-images.githubusercontent.com/48336859/59878979-4cc2d280-936f-11e9-8016-3c22bd1ecf5c.png)

- I don't think we should use the same cancel/next buttons as in the modal. In the wizard inline it gets stretched too far and looks really odd, barely even like they are buttons.
- I would suggest that we treat the buttons more like they were in Carbon 9, with padding around them in the footer, something like this:

![Screen Shot 2019-06-20 at 3 30 25 PM](https://user-images.githubusercontent.com/48336859/59879454-5bf65000-9370-11e9-99cc-a133badf4dad.png)

**4. Navigation Bar**
![Screen Shot 2019-06-20 at 3 35 09 PM](https://user-images.githubusercontent.com/48336859/59879813-33228a80-9371-11e9-81ce-15f8af4d7c73.png)
![Screen Shot 2019-06-20 at 3 36 17 PM](https://user-images.githubusercontent.com/48336859/59879814-33228a80-9371-11e9-805a-5ca6c34bdbed.png)

- A question for @lukefirth... Should the bar under the tab be lined up with the description text, or should the tab text line up with the description text (as it is now)? 

**5. Page Hero**

- Can we make some updates here based on the specs? This might apply to the navigation bar too...
- h1 should be #171717 at 20px (1.75rem). Margin-bottom should be 16px.
- The description text below the H1 should be #17171 at 14px(.875 rem). Line-height should be 20px, margin-bottom should be 16px.
- I also think we need to make updates to the "with section" and "has breadcrumb" parts to use the breadcrumb style from Carbon

![Screen Shot 2019-06-20 at 3 50 58 PM](https://user-images.githubusercontent.com/48336859/59880667-39b20180-9373-11e9-8118-a3a35080c45b.png)

**6. Resource List**
- Weirdly specific, but the pencil icon on the "with action" version is still the Carbon 9 blue

**7. Table**
- I have some stuff here, but might open a separate issue (there's so many table examples)

**Comment by davidicus** [comment]
Addressing @amymillett comments above. 

>1. Tile 

@lukefirth If there is not a reason why this differs I will align with the Carbon version

>2. Filedrop - Drag and Drop

Changed link color

>3. Wizard Inline

Without commenting on whether it looks good or not I will just say that the current implementation seems to be in line with how Carbon treats these modal buttons. 
![image](https://user-images.githubusercontent.com/1590966/60460092-d34d9e80-9c10-11e9-90eb-eb8db566ece6.png)

@lukefirth @amymillett Whatever you both think. Can we document and instruct in this comment thread. 

>4. Navigation Bar

@lukefirth please advise. I think we should line up the line with the content below so padding is consistent. 

>5. Page Hero

I have made first two changes. The breadcrumbs have an issue to covert to using base carbon breadcrumbs. 

>6. Resource List

Changed fill color to blue60

>7. Will address table notes in the issue #339

**Comment by lukefirth** [comment]
@davidicus 

1. Tile - sounds good to go with the carbon hover state.

3. Agreed on that's how they currently do it. The movement in carbon on the topic can be seen here: https://github.com/carbon-design-system/carbon/issues/2922 In short, part of this is that they are considering a new 'progress modal' which would be pretty much what we're building here (although not inline). There is no official design recommendation from the carbon team on that yet, other than Chris' quick mockups in the original slack thread (which I based my mockup above on).

- At the end of the day, I have personal pref to not stretch the buttons full width for inline wizards, but I'll go with whatever the experts say is the recommended visual direction (@amymillett )

4. Navigation bar. I'm open. Feels like you are right @davidicus - line up the tab underline rather than the text with other content on the page giving a nice clear & consistent empty block as the left page padding.

**Comment by tay1orjones** [comment]
Did #389 fully close this?  Seems complete from my cursory glance. 

If not, what's left?

**Comment by davidicus** [comment]
Work has been done
