### ISSUE TITLE
[Release] v2.0.0

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#304]
Epic containing all the work items leading up to v2 release.

### Must Haves:
- [x] Create `v2` label for GitHub issues feeding into v2
- [x] Create `beta` branch to contain this work
- [x] Update semantic release to publish prerelease from `beta` - #276 
- [x] Update storybook deploy to support `beta` branch, consistent static url - #305 
- [x] Upgrade Carbon to v10, Update our components #154
- [x] Consolidate our components with Carbon variants - #369 
- [x] Provide wrapper components for all Carbon react components, #355 
- [x] Update to Carbon v10.4 - #436
- [ ] Merge updates from `master` into `beta` - #437

### Nice To Haves:

- [ ] Align Components to Patterns -  #354
- [x] Theme Storybook for consistent branding - #309
- [ ] Dashboard/monitoring components updated to support Carbon v10 - #306 
  - These are unlikely to be migrated before other updates have been made. They're currently experimental and baked with Carbon v9. Without the update, these components will likely not be included in the initial v2 release although we can upgrade them at any point thereafter. Existing development requirements can continue to be delivered to the v.1.x release
- [ ] Unify Layout, Spacing, and Color to Carbon Tokens #303 
- [ ] Refactor styling approach from styled-components to scss to align with Carbon - #370 

~- [ ] Migrate WIoT Theme file to this library - #332~

**Comment by tay1orjones** [comment]
Items to accomplish during or shortly after the release:

- [ ] Update links in the readme, no need to point to beta branch anymore.
- [ ] Create v1.x maintenance branch - review semantic release documentation to ensure we config this properly
- [ ] Create a v1 label, add this label to all current issues open for the v1 workstream. 
- [ ] Update issue template to ask submitter for the version of the lib they're opening an issue against
- [ ] Any other beta-specific things we need to update?
